name: wallpaper_setter
description:
  "A Flutter plugin for setting device wallpapers directly from your app.
  Uses the default Android system wallpaper picker UI to set wallpapers from 
  asset or network images for the home screen, lock screen, or both."

version: 0.0.4
homepage: https://github.com/iamporag/wallpaper_setter
repository: https://github.com/iamporag/wallpaper_setter/issues
license: MIT

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.iamporag.wallpaper_setter
        pluginClass: WallpaperSetterPlugin
      ios:
        pluginClass: WallpaperSetterPlugin

  assets:
    - assets/demo.gif